version: "3.9"
services:
 web1:
  image: node:latest
  container_name: server1
  ports:
   - "8080:8080"
  command: ["bin/bash"]
  volumes:
   - ./:/code
  stdin_open: true
  tty: true
 web2:
  image: node:latest
  container_name: server2
  ports:
   - "3000:3000"
  command: ["bin/bash"]
  volumes:
   - ./:/code
  stdin_open: true
  tty: true